version: "3.9" # optional since v1.27.0
services:
  web:
    build: .
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  mongodb:
    image: mongodb
volumes:
  logvolume01: {}
