version: '2'
services:
  web:
    build: .
    networks:
      - mongo-network
  mongodb:
    image: mongo:5.0.6
    ports:
      - "27050:27017"
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge
